shared:
  twilio_account_sid:  <%= ENV["SECRET_KEY_SID"] %>
  twilio_auth_token:  <%= ENV["SECRET_KEY_TOKEN"] %>
  twilio_phone_number:  <%= ENV["SECRET_KEY_NUMBER"] %>
  rspotify_client_id: <%= ENV["SECRET_KEY_CLIENT_ID"] %>
  rspotify_client_secret: <%= ENV["SECRET_KEY_CLIENT_SECRET"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


